### ISSUE TITLE
Nextcloud Talk - should have one-click record teleconference integrated

### ISSUE THREAD

**Issue by OrcVole** [nextcloud/nextcloud-talk-recording#19]
It is expected of teleconference applications to have a "record" button integrated into the tool. 

To have to set up an entirely new server simply to record a teleconference is far from what most people expect and require these days.

**Comment by nickvergessen** [comment]
Feel free to use https://github.com/nextcloud/all-in-one then.

There are various reasons why in bigger/enterprise setups it is not desired to have everything in the same server, especially since a browser with all its dependencies has to be installed.
This can be worked around by using docker (like in the all-in-one), but we can also not make docker a requirement for deploying Talk. 🤷
